### ISSUE TITLE
section achivement

### ISSUE THREAD

**Issue by sana-ben036** [sana-ben036/Agence_Web_version_2_2#4]
merci de s'occuper de la page achievement au niveau de code avec un petit rappel qui va la représenter sur page d’accueil  

- [x] HTML
- [x]  SASS
- [x] JQ plus documentation

**Comment by mednajjar** [comment]
merci de vérifier la page About avec la responsivité, si il y a quelque chose a changé! je suis a votre disposition. 
merci.

**Comment by sana-ben036** [comment]
le titre About : si vous pouvez le remplacer pour éviter la répétition
proposition : your best choice - why us - our value ...

**Comment by sana-ben036** [comment]
la section est validé
