### ISSUE TITLE
section client

### ISSUE THREAD

**Issue by sana-ben036** [sana-ben036/Agence_Web_version_2_2#5]
merci de s'occuper de la page client au niveau de code avec un petit rappel qui va la représenter sur page d’accueil  

- [x] HTML
- [x]  SASS
- [x] JQ plus documentation

**Comment by sana-ben036** [comment]
veuillez améliorer la responsive et la gestion des espaces

**Comment by theycallmeCryptic** [comment]
wa faaaaaaaaaat
